### PR TITLE
Handle external updates again

### PR DESCRIPTION
**Pull request by aeriksson**
This fixes the issue with #28 where focus is lost when editing input fields.

### CODE REVIEW

**Comment by oborder** [comment]
Hi,

I am writing this here instead as an issue, I hope this is not inappropriate..

I am trying to disable some fields depending on the doc state. Without this patch input disabled state is not in sync with the doc (it seems to pickup last state from doc).

I have changed bind for :input-field to include disabled property, and it seems to work fine, but am unsure if this is the right approach.

https://github.com/oborder/reagent-forms/commit/422c6798bc5a91bf8e15398797bf58c038a51567

**Comment by yogthos** [comment]
@oborder it looks like the approach outlined in this issue won't really work, and the approach of adding the disabled property seems reasonable to me. If you'd like to pr that I can cut a new release.

**Comment by oborder** [comment]
@yogthos I may be doing something wrong, but my patch is not working ok withouth this patch. It seems to always render disabled state from previous document state. For example if I load document which should have some field disabled after document which doesnt have it disabled, the field will still be enabled, and then on next change of document it will be disabled.. I am not really sure what is causing this, and how to fix it?

**Comment by yogthos** [comment]
@oborder this patch doesn't work because it doesn't allow for local state in components. I was just keeping it open as a reminder to find a workaround for the issue. I should probably just close it and create an issue instead to avoid confusion.

**Pull request closed without merging**
